=== igorvood/uasp/uasp-streaming-input-convertor/scripts/multi-schema/schemas/issuing-operation-2.1.json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "title" : "Issuing Operation",
  "type" : "object",
  "additionalProperties" : true,
  "description" : "issuing operation: on/off us*auth/fin",
  "properties" : {
    "id" : {
      "type" : "string",
      "description" : "Unique within processing center, action type"
    },
    "prevId" : {
      "type" : "string",
      "description" : "Reference to previous"
    },
    "chain" : {
      "$ref" : "#/definitions/OperationChain"
    },
    "actionType" : {
      "type" : "string",
      "enum" : [ "Authorization", "AuthorizationReversal", "AuthorizationAdjustment", "Presentment", "PresentmentReversal", "PresentmentAdjustment", "Chargeback", "ChargebackPartial", "ChargebackReversal", "ChargebackAdjustment", "Representment", "RepresentmentPartial", "RepresentmentReversal", "Acknowledgement", "WriteOff" ],
      "description" : "Chain step of business service (defined by service type)"
    },
    "comment" : {
      "type" : "string"
    },
    "reasonDetails" : {
      "type" : "string"
    },
    "card" : {
      "$ref" : "#/definitions/IssuingCardRef"
    },
    "account" : {
      "$ref" : "#/definitions/IssuingAccountRef"
    },
    "requestedAmount" : {
      "$ref" : "#/definitions/OperationAmount"
    },
    "routing" : {
      "oneOf" : [ {
        "$ref" : "#/definitions/IncomingRouting"
      }, {
        "$ref" : "#/definitions/OutgoingRouting"
      }, {
        "$ref" : "#/definitions/OnUsRouting"
      }, {
        "$ref" : "#/definitions/InternalRouting"
      } ]
    },
    "pointOfService" : {
      "$ref" : "#/definitions/PointOfService"
    },
    "processing" : {
      "$ref" : "#/definitions/IssuingOperationProcessing"
    },
    "paymentDetails" : {
      "$ref" : "#/definitions/PaymentDetails",
      "description" : "Payment attributes"
    },
    "counterpartyPaymentDetails" : {
      "$ref" : "#/definitions/PaymentDetails",
      "description" : "Counterparty payment attributes"
    },
    "taggedData" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "string"
      }
    },
    "additionalData" : {
      "type" : "object",
      "additionalProperties" : { },
      "description" : "additional custom data"
    }
  },
  "required" : [ "id", "chain", "actionType", "account", "requestedAmount", "routing", "processing", "taggedData" ],
  "definitions" : {
    "OperationChain" : {
      "type" : "object",
      "additionalProperties" : true,
      "description" : "operation chain description (related to the original operation in chain)",
      "properties" : {
        "id" : {
          "type" : "string",
          "description" : "~id of the first operation in chain"
        },
        "ref" : {
          "$ref" : "#/definitions/OperationChainRef"
        },
        "auth" : {
          "$ref" : "#/definitions/OperationChainAuth"
        },
        "serviceType" : {
          "type" : "string",
          "description" : "business service classification"
        },
        "serviceDateTime" : {
          "type" : "string",
          "format" : "date-time",
          "description" : "bill datetime (primary action datetime)"
        },
        "additionalData" : {
          "type" : "object",
          "additionalProperties" : { },
          "description" : "additional custom data"
        }
      },
      "required" : [ "id", "serviceType" ]
    },
    "OperationChainRef" : {
      "type" : "object",
      "additionalProperties" : true,
      "description" : "chain reference set",
      "properties" : {
        "authCode" : {
          "type" : "string"
        },
        "rrn" : {
          "type" : "string",
          "description" : "retrieval reference number"
        },
        "tref" : {
          "type" : "string",
          "description" : "payment scheme reference number"
        },
        "srn" : {
          "type" : "string",
          "description" : "system reference number"
        },
        "arn" : {
          "type" : "string",
          "description" : "acquirer reference number"
        },
        "additionalData" : {
          "type" : "object",
          "additionalProperties" : { },
          "description" : "additional custom data"
        }
      }
    },
    "OperationChainAuth" : {
      "type" : "object",
      "additionalProperties" : true,
      "description" : "conditions when transaction has been approved",
      "properties" : {
        "conditions" : {
          "type" : "array",
          "items" : {
            "type" : "string"
          },
          "description" : "tag list from trans attribute"
        },
        "isContactless" : {
          "type" : "boolean"
        },
        "isPinBased" : {
          "type" : "boolean"
        },
        "isRecurring" : {
          "type" : "boolean"
        },
        "isEcom" : {
          "type" : "boolean"
        },
        "is3DS" : {
          "type" : "boolean"
        },
        "tokenType" : {
          "type" : "string",
          "description" : "e.g. ApplePay, GooglePay ..."
        },
        "additionalData" : {
          "type" : "object",
          "additionalProperties" : { },
          "description" : "additional custom data"
        }
      },
      "required" : [ "conditions" ]
    },
    "IssuingCardRef" : {
      "type" : "object",
      "additionalProperties" : true,
      "description" : "details of the operation payment instrument",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "externalId" : {
          "type" : "string",
          "description" : "card identifier in bank system"
        },
        "pan" : {
          "type" : "string",
          "description" : "masked or not"
        },
        "plastic" : {
          "$ref" : "#/definitions/CardPlastic"
        },
        "additionalData" : {
          "type" : "object",
          "additionalProperties" : { },
          "description" : "additional custom data"
        }
      },
      "required" : [ "id", "pan" ]
    },
    "CardPlastic" : {
      "type" : "object",
      "additionalProperties" : true,
      "properties" : {
        "expire" : {
          "type" : "string",
          "description" : "YYMM"
        },
        "seqvN" : {
          "type" : "string"
        },
        "additionalData" : {
          "type" : "object",
          "additionalProperties" : { },
          "description" : "additional custom data"
        }
      }
    },
    "IssuingAccountRef" : {
      "type" : "object",
      "additionalProperties" : true,
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "iban" : {
          "type" : "string",
          "description" : "International bank account number (IBAN)"
        },
        "bic" : {
          "type" : "string",
          "description" : "Bank Identifier Code (BIC)"
        },
        "accountNumber" : {
          "type" : "string",
          "description" : "Account Number"
        },
        "contractNumber" : {
          "type" : "string",
          "description" : "Contract Number"
        },
        "additionalData" : {
          "type" : "object",
          "additionalProperties" : { },
          "description" : "additional custom data"
        }
      },
      "required" : [ "id" ]
    },
    "OperationAmount" : {
      "type" : "object",
      "additionalProperties" : true,
      "description" : "amounts submitted by operation initiator and payment scheme in transaction message",
      "properties" : {
        "paymentDirection" : {
          "type" : "string",
          "enum" : [ "Debit", "Credit", "None" ],
          "description" : "accounting direction regarding to operation target"
        },
        "transaction" : {
          "$ref" : "#/definitions/Money"
        },
        "cashback" : {
          "$ref" : "#/definitions/Money"
        },
        "billing" : {
          "$ref" : "#/definitions/Money",
          "description" : "named also settlement"
        },
        "additionalData" : {
          "type" : "object",
          "additionalProperties" : { },
          "description" : "additional custom data"
        }
      },
      "required" : [ "paymentDirection" ]
    },
    "Money" : {
      "type" : "object",
      "additionalProperties" : true,
      "properties" : {
        "amount" : {
          "type" : "string"
        },
        "currency" : {
          "type" : "string"
        },
        "formatted" : {
          "type" : "string"
        }
      },
      "required" : [ "amount", "currency" ]
    },
    "IncomingRouting" : {
      "type" : "object",
      "additionalProperties" : true,
      "properties" : {
        "routingType" : {
          "type" : "string",
          "enum" : [ "Incoming" ],
          "default" : "Incoming"
        },
        "paymentScheme" : {
          "type" : "string",
          "description" : "payment scheme 'name'. e.g.: VISA, MC ..."
        },
        "clearingDate" : {
          "type" : "string",
          "format" : "date",
          "description" : "in term of payment scheme clearing process"
        },
        "sourceMemberId" : {
          "type" : "string"
        },
        "receivingMemberId" : {
          "type" : "string"
        },
        "additionalData" : {
          "type" : "object",
          "additionalProperties" : { },
          "description" : "additional custom data"
        },
        "direction" : {
          "type" : "string",
          "enum" : [ "Incoming", "Outgoing", "Internal" ]
        }
      },
      "title" : "Incoming",
      "required" : [ "routingType", "paymentScheme", "sourceMemberId", "receivingMemberId", "direction" ]
    },
    "OutgoingRouting" : {
      "type" : "object",
      "additionalProperties" : true,
      "properties" : {
        "routingType" : {
          "type" : "string",
          "enum" : [ "Outgoing" ],
          "default" : "Outgoing"
        },
        "paymentScheme" : {
          "type" : "string",
          "description" : "payment scheme 'name'. e.g.: VISA, MC ..."
        },
        "clearingDate" : {
          "type" : "string",
          "format" : "date",
          "description" : "in term of payment scheme clearing process"
        },
        "targetMemberId" : {
          "type" : "string"
        },
        "sendingBin" : {
          "type" : "string"
        },
        "sendingMemberId" : {
          "type" : "string"
        },
        "additionalData" : {
          "type" : "object",
          "additionalProperties" : { },
          "description" : "additional custom data"
        },
        "direction" : {
          "type" : "string",
          "enum" : [ "Incoming", "Outgoing", "Internal" ]
        }
      },
      "title" : "Outgoing",
      "required" : [ "routingType", "paymentScheme", "targetMemberId", "sendingMemberId", "direction" ]
    },
    "OnUsRouting" : {
      "type" : "object",
      "additionalProperties" : true,
      "properties" : {
        "routingType" : {
          "type" : "string",
          "enum" : [ "OnUs" ],
          "default" : "OnUs"
        },
        "direction" : {
          "type" : "string",
          "enum" : [ "Incoming", "Outgoing", "Internal" ]
        },
        "additionalData" : {
          "type" : "object",
          "additionalProperties" : { },
          "description" : "additional custom data"
        }
      },
      "title" : "OnUs",
      "required" : [ "routingType", "direction" ]
    },
    "InternalRouting" : {
      "type" : "object",
      "additionalProperties" : true,
      "properties" : {
        "routingType" : {
          "type" : "string",
          "enum" : [ "Internal" ],
          "default" : "Internal"
        },
        "additionalData" : {
          "type" : "object",
          "additionalProperties" : { },
          "description" : "additional custom data"
        },
        "direction" : {
          "type" : "string",
          "enum" : [ "Incoming", "Outgoing", "Internal" ]
        }
      },
      "title" : "Internal",
      "required" : [ "routingType", "direction" ]
    },
    "PointOfService" : {
      "type" : "object",
      "additionalProperties" : true,
      "description" : "for particular operation",
      "properties" : {
        "country" : {
          "type" : "string"
        },
        "city" : {
          "type" : "string"
        },
        "location" : {
          "type" : "string"
        },
        "merchantName" : {
          "type" : "string"
        },
        "mcc" : {
          "type" : "string"
        },
        "merchantId" : {
          "type" : "string"
        },
        "terminalId" : {
          "type" : "string"
        },
        "terminalType" : {
          "type" : "string",
          "enum" : [ "CAT", "ATM", "POS", "WEB", "IMPRINTER", "ECOMMERCE", "MPOS" ],
          "description" : "by trans attributes"
        },
        "institution" : {
          "$ref" : "#/definitions/FinancialInstitution"
        },
        "additionalData" : {
          "type" : "object",
          "additionalProperties" : { },
          "description" : "additional custom data"
        }
      }
    },
    "FinancialInstitution" : {
      "type" : "object",
      "additionalProperties" : true,
      "description" : "financial institution identification",
      "properties" : {
        "bank" : {
          "type" : "string"
        },
        "branch" : {
          "type" : "string"
        },
        "country" : {
          "type" : "string",
          "description" : "ISO 3166 Alfa(3) country code"
        },
        "office" : {
          "type" : "string"
        },
        "additionalData" : {
          "type" : "object",
          "additionalProperties" : { },
          "description" : "additional custom data"
        }
      },
      "required" : [ "bank", "branch", "country" ]
    },
    "IssuingOperationProcessing" : {
      "type" : "object",
      "additionalProperties" : true,
      "description" : "processing results (issuing specific)",
      "properties" : {
        "billingDate" : {
          "type" : "string",
          "format" : "date",
          "description" : "target account start of billing"
        },
        "availableAmount" : {
          "$ref" : "#/definitions/Money",
          "description" : "payment instrument available amount before the operation (on-us card auth only)"
        },
        "baseAmount" : {
          "$ref" : "#/definitions/Money",
          "description" : "total by entries: requested amount in account currency"
        },
        "feeAmount" : {
          "$ref" : "#/definitions/Money",
          "description" : "total by entries: fee amount in account currency"
        },
        "additionalData" : {
          "type" : "object",
          "additionalProperties" : { },
          "description" : "additional custom data"
        },
        "resolution" : {
          "type" : "string",
          "enum" : [ "Accepted", "Rejected" ]
        },
        "resultCode" : {
          "type" : "string"
        },
        "chainStage" : {
          "type" : "string",
          "enum" : [ "Authorized", "Presented", "Settled", "Reversed", "Disputed", "Rejected" ],
          "description" : "service result stage after the operation"
        },
        "processedAt" : {
          "type" : "string",
          "format" : "date-time",
          "description" : "processing time"
        },
        "effectiveDate" : {
          "type" : "string",
          "format" : "date",
          "description" : "in terms of bank date"
        },
        "fxRateId" : {
          "type" : "string"
        }
      },
      "required" : [ "resolution", "resultCode", "chainStage", "processedAt", "effectiveDate" ]
    },
    "PaymentDetails" : {
      "type" : "object",
      "additionalProperties" : true,
      "description" : "Party Info",
      "properties" : {
        "partyType" : {
          "type" : "string",
          "enum" : [ "Payer", "Beneficiary" ],
          "description" : "Party type"
        },
        "party" : {
          "$ref" : "#/definitions/PartyInfo",
          "description" : "Party"
        },
        "bank" : {
          "$ref" : "#/definitions/PartyInfo",
          "description" : "Party bank Info"
        },
        "corrBank" : {
          "$ref" : "#/definitions/PartyInfo",
          "description" : "Party correspondent bank Info"
        }
      }
    },
    "PartyInfo" : {
      "type" : "object",
      "additionalProperties" : true,
      "properties" : {
        "name" : {
          "type" : "string",
          "description" : "Party name"
        },
        "accountInfo" : {
          "$ref" : "#/definitions/PartyAccount"
        },
        "taxInfo" : {
          "$ref" : "#/definitions/PartyTax"
        },
        "taggedData" : {
          "type" : "object",
          "additionalProperties" : {
            "type" : "string"
          }
        },
        "additionalData" : {
          "type" : "object",
          "additionalProperties" : { },
          "description" : "additional custom data"
        }
      }
    },
    "PartyAccount" : {
      "type" : "object",
      "additionalProperties" : true,
      "description" : "Party account attributes",
      "properties" : {
        "accountNumber" : {
          "type" : "string",
          "description" : "Account number"
        },
        "accountMemberId" : {
          "type" : "string",
          "description" : "Account member id"
        }
      }
    },
    "PartyTax" : {
      "type" : "object",
      "additionalProperties" : true,
      "description" : "Party tax attributes",
      "properties" : {
        "itn" : {
          "type" : "string",
          "description" : "Individual tax number"
        },
        "taxPosition" : {
          "type" : "string",
          "description" : "Tax position"
        }
      }
    }
  }
}

=== igorvood/uasp/uasp-streaming-input-convertor/src/test/resources/way4-test1.json
{
  "id": "WWYC8M2SRG1V",
  "chain": {
    "id": "995599",
    "ref": {
      "authCode": "K9YGM29YJJMA",
      "rrn": "LLFXG2Y5FQTX",
      "srn": "D02UTKZZFXSE"
    },
    "serviceType": "I7",
    "serviceTypeExtension": "731500-03",
    "serviceDateTime": "2022-08-26T10:35:41"
  },
  "actionType": "Presentment",
  "card": {
    "id": "1084687030",
    "externalId": "40914810200009000369",
    "pan": "529938******8812",
    "cardType": {
      "paymentScheme": "Mastercard",
      "memberId": "007703",
      "bin": "529938",
      "country": "RUS",
      "region": "Europe",
      "serviceCode": "101",
      "isChip": false,
      "isLocal": false,
      "psProduct": "MCS",
      "psCardBrand": "MCC",
      "psFundingSource": "Credit"
    },
    "plastic": {
      "expire": "2607",
      "seqvN": "1"
    },
    "client": {
      "id": "91667956",
      "externalId": "ClientNum681030",
      "clientCategory": "Private"
    }
  },
  "account": {
    "id": "1084687020",
    "iban": "40914810200009000369",
    "accountNumber": "40914810200009000369",
    "contractNumber": "9800-P-311661",
    "client": {
      "id": "91667956",
      "externalId": "ClientNum681030",
      "clientCategory": "Private"
    }
  },
  "requestedAmount": {
    "paymentDirection": "Debit",
    "transaction": {
      "amount": "4929.87000",
      "currency": "RUR"
    },
    "billing": {
      "amount": "2300.00",
      "currency": "RUR"
    }
  },
  "routing": {
    "direction": "Incoming",
    "routingType": "OnUs"
  },
  "pointOfService": {
    "terminalId": "11111111",
    "terminalType": "ECOMMERCE",
    "mcc": "6536",
    "institution": {
      "bank": "9800",
      "branch": "9800",
      "country": "RUS"
    }
  },
  "processing": {
    "billingDate": "2021-07-01",
    "availableAmount": {
      "amount": "19000.00",
      "currency": "RUR"
    },
    "baseAmount": {
      "amount": "2300.00",
      "currency": "USD"
    },
    "resolution": "Accepted",
    "resultCode": "SITV3FYHHXYX",
    "chainStage": "Authorized",
    "processedAt": "2022-08-26T07:35:41Z",
    "effectiveDate": "2022-08-26",
    "fxRateId": "371860000001"
  },
  "taggedData": {
    "PINR": "0",
    "TGTCC": "RUS",
    "PRODUCT_ID": "MCS",
    "APRPD_IND": "N",
    "CARD_AFS": "C",
    "CARD_PTI": "1",
    "SRCCC": "RUS",
    "T_USG": "AKR"
  }
}

=== igorvood/uasp/uasp-streaming-input-convertor/src/test/resources/payload/payload-Успешная авторизация покупки на сумму 2 300р.json
{
  "id": "494110",
  "chain": {
    "id": "494110",
    "ref": {
      "rrn": "118312163001",
      "srn": "L1831207N65A"
    },
    "auth": {
      "conditions": [
        "POS",
        "TERM",
        "TERM_CHIP",
        "TERM_TRACK",
        "TERM_KEY_ENTRY",
        "TERM_PIN",
        "AUTHENTICATED",
        "AUTH_MERCH",
        "TRANS_AUTH",
        "SBT",
        "SBT_MAN",
        "CARD",
        "CARDHOLDER",
        "MERCH",
        "KEY_ENTRY",
        "TERM_MSV",
        "TERM_NO_CC",
        "TERM_TRACK_WRITE",
        "TERM_PRINT",
        "TERM_DISPLAY",
        "TERM_ONP_CA",
        "TERM_4_PIN"
      ],
      "isContactless": false,
      "isPinBased": false,
      "isRecurring": false,
      "isEcom": false,
      "is3DS": false
    },
    "serviceType": "I5",
    "serviceDateTime": "2021-07-02T15:16:23"
  },
  "actionType": "Authorization",
  "card": {
    "id": "1084687030",
    "externalId": "40914810200009000369",
    "pan": "529938******8812",
    "cardType": {
      "paymentScheme": "Mastercard",
      "memberId": "007703",
      "bin": "529938",
      "country": "RUS",
      "region": "Europe",
      "serviceCode": "101",
      "isChip": false,
      "isLocal": false,
      "psProduct": "MCS",
      "psCardBrand": "MCC",
      "psFundingSource": "Credit"
    },
    "plastic": {
      "expire": "2607"
    },
    "client": {
      "id": "2157291480",
      "externalId": "ClientNum 681030",
      "clientCategory": "Private"
    }
  },
  "account": {
    "id": "1084687020",
    "iban": "40914810200009000369",
    "accountNumber": "40914810200009000369",
    "contractNumber": "9800-P-311661",
    "client": {
      "id": "2157291480",
      "externalId": "ClientNum 681030",
      "clientCategory": "Private"
    }
  },
  "requestedAmount": {
    "paymentDirection": "Debit",
    "transaction": {
      "amount": "100020.00",
      "currency": "RUR"
    },
    "billing": {
      "amount": "100020.00",
      "currency": "RUR"
    }
  },
  "routing": {
    "direction": "Incoming",
    "routingType": "OnUs"
  },
  "pointOfService": {
    "country": "RUS",
    "region": "10",
    "city": "MOSCOW",
    "merchantName": "Address1",
    "mcc": "5193",
    "merchantId": "999999999900000",
    "terminalId": "99999999",
    "terminalType": "POS",
    "institution": {
      "bank": "9800",
      "branch": "9800",
      "country": "RUS"
    }
  },
  "processing": {
    "billingDate": "2021-07-01",
    "availableAmount": {
      "amount": "17000.00",
      "currency": "RUR"
    },
    "baseAmount": {
      "amount": "-100020.00",
      "currency": "RUR"
    },
    "resolution": "Rejected",
    "resultCode": "54",
    "chainStage": "Rejected",
    "processedAt": "2021-07-02T12:16:24Z",
    "effectiveDate": "2021-04-10",
    "fxRateId": "371860000001"
  },
  "taggedData": {
    "BCURR": "UNKNOWN",
    "DE19": "643",
    "VPD": "05",
    "TGTCC": "RUS",
    "PRODUCT_ID": "MCS",
    "APRPD_IND": "N",
    "CARD_AFS": "C",
    "SRCCC": "RUS",
    "T_USG": "KOR",
    "ISS_FMS_RQ": "",
    "FMS_NEXT_BERTLV": "F022F51EC10BT2156729200C20BT2157291480"
  }
}
