=== igorvood/uasp/uasp-streaming-input-convertor/scripts/multi-schema/schemas/loyalty-1.0.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "mdmId": {
      "type": "string"
    },
    "actualTime": {
      "type": "string"
    },
    "loyaltyPrograms": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "code": {
              "type": "string"
            },
            "status": {
              "type": "string"
            },
            "options": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "startDate": {
                      "type": "string"
                    },
                    "closeDate": {
                      "type": "string"
                    },
                    "createTime": {
                      "type": "string"
                    },
                    "operatorId": {
                      "type": "null"
                    }
                  },
                  "required": [
                    "code",
                    "name",
                    "startDate",
                    "closeDate",
                    "createTime",
                    "operatorId"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "startDate": {
                      "type": "string"
                    },
                    "closeDate": {
                      "type": "null"
                    },
                    "createTime": {
                      "type": "string"
                    },
                    "operatorId": {
                      "type": "null"
                    }
                  },
                  "required": [
                    "code",
                    "name",
                    "startDate",
                    "closeDate",
                    "createTime",
                    "operatorId"
                  ]
                }
              ]
            },
            "accounts": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "currency": {
                      "type": "string"
                    },
                    "balance": {
                      "type": "integer"
                    }
                  },
                  "required": [
                    "currency",
                    "balance"
                  ]
                }
              ]
            }
          },
          "required": [
            "name",
            "code",
            "status",
            "options",
            "accounts"
          ]
        }
      ]
    },
    "eventType": {
      "type": "string"
    }
  },
  "required": [
    "mdmId",
    "actualTime",
    "loyaltyPrograms",
    "eventType"
  ]
}

=== igorvood/uasp/uasp-streaming-input-convertor/src/test/resources/loyalty-test.json
{
  "mdmId": "32542135",
  "actualTime": "2022-10-19T09:25:16",
  "loyaltyPrograms": [
    {
      "name": "Программа Мультибонус",
      "code": "MULTIBONUS",
      "status": "ACTIVE",
      "options": [
        {
          "code": "CBPRIV",
          "name": "Привилегия",
          "startDate": "2022-09-01",
          "closeDate": "2022-09-30",
          "createTime": "2022-08-19T09:25:16",
          "operatorId": null
        },
        {
          "code": "NoBonus",
          "name": "Отключена опция",
          "startDate": "2022-10-01",
          "closeDate": null,
          "createTime": "2022-09-19T09:25:16",
          "operatorId": null
        }
      ],
      "accounts": [
        {
          "currency": "CB",
          "balance": 1235
        }
      ]
    }
  ],
  "eventType": "NEW_OPTION"
}
